### ISSUE TITLE
ArrayOutBoundOfIndex in JDBC Driver

### ISSUE THREAD

**Issue by fabiocmazzo** [bitnine-oss/agensgraph-jdbc#46]
Hello, 
    
       I'm writing a OGM Framwork for AgensGraph and  when i use Optional Match with deep in relationship i get this error:

 `java.lang.ArrayIndexOutOfBoundsException: 2
	at org.postgresql.jdbc.PgArray.buildArrayList(PgArray.java:442)
	at org.postgresql.jdbc.PgArray.getBaseTypeName(PgArray.java:779)
	at org.postgresql.jdbc.PgArray.getBaseType(PgArray.java:775)
	at com.intellij.database.remote.jdbc.impl.JdbcRemoteObject.wrapIfNeeded(JdbcRemoteObject.java:32)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.createInfoIfNeeded(RemoteResultSetImpl.java:1350)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObject(RemoteResultSetImpl.java:1272)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getCurrentRow(RemoteResultSetImpl.java:1249)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObjects(RemoteResultSetImpl.java:1229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
  Cypher to reproduce the error:
   `MATCH (a) OPTIONAL MATCH (a)-[b*0..2]-() RETURN *`

Thank You,

**Comment by zzl221000** [comment]
Hi @bylee5 ,
I ran into the same problem.
I debug the getArray method
` private synchronized void buildArrayList() throws SQLException {
        if (this.arrayList == null) {
            this.arrayList = new PgArray.PgArrayList();
            char delim = this.connection.getTypeInfo().getArrayDelimiter(this.oid);
            if (this.fieldString != null) {
                char[] chars = this.fieldString.toCharArray();
                StringBuilder buffer = null;
                boolean insideString = false;
                boolean wasInsideString = false;
                List<PgArray.PgArrayList> dims = new ArrayList();
                PgArray.PgArrayList curArray = this.arrayList;
                int startOffset = 0;
                if (chars[0] == '[') {
                    while(chars[startOffset] != '=') {
                        ++startOffset;
                    }`
PgArray.getArray use the buildArrayList(). the fieldString does not contain "=" , This statement will always execute ++startOffset

**Comment by bylee5** [comment]
Do you use the ResultSet.getArray() method?
